services:
  db:
    image: mariadb:10.11
    container_name: wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wp-headless
    restart: always
    ports:
      - "5053:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://wp.glassgallery.my.id');
        define('WP_SITEURL', 'https://wp.glassgallery.my.id');
        define('FORCE_SSL_ADMIN', true);
        /* HTTPS Detection */
    volumes:
      - ./wp_data:/var/var/www/html
    depends_on:
      - db
